---
kind: Service
apiVersion: v1
metadata:
  name: node-example
spec:
  type: LoadBalancer
  selector:
    app: node-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: node-app
      protocol: TCP
      port: 3000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: node
        image: docker.pkg.github.com/tcbyrd/node-k8s/node-k8s:0.0.2
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: regcred
