---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: node
        image: docker.pkg.github.com/tcbyrd/node-k8s/node-k8s:0.0.1
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: regcred
