apiVersion: v1
kind: Service
metadata:
    name: "tcbyrdk8sdev-ac89"
    labels:
        app: "tcbyrdk8sdev-ac89"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "tcbyrdk8sdev-ac89"