apiVersion: v1
kind: Service
metadata:
    name: "examplekubernetescluster4381b888-da92"
    labels:
        app: "examplekubernetescluster4381b888-da92"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "examplekubernetescluster4381b888-da92"