apiVersion: v1
kind: Service
metadata:
    name: "tcbyrdk8sdev-ac89"
    labels:
        app: "tcbyrdk8sdev-ac89"
spec:
    type: ClusterIP
    ports:
    - port: 3000
    selector:
        app: "tcbyrdk8sdev-ac89"
