# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build container

on:
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_75A57EBDB84947A09A48290C6E2122C2 }}
    - name: Build and Push a PR
      if: github.event_name == 'pull_request'
      run: |
        docker build . -t ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha }} --build-arg GITHUB_SHA=${{ github.event.pull_request.head.sha }}
        docker push ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha }}
    - name: Build and Push from workflow dispatch
      if: github.event_name == 'workflow_dispatch'
      run: |
        docker build . -t ghcr.io/${{ github.repository }}:${{ github.sha }} --build-arg GITHUB_SHA=${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
      

      
